// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjaZls5Uz_IThIwb_z8YGVKFMdcjUx3xc',
    appId: '1:518969593507:web:3bbc7342bca61687b7b916',
    messagingSenderId: '518969593507',
    projectId: 'bema-8f7d2',
    authDomain: 'bema-8f7d2.firebaseapp.com',
    storageBucket: 'bema-8f7d2.appspot.com',
    measurementId: 'G-98R5RJJLQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8-sml1xtMkX8HC45GZmwesHF_brCd9M',
    appId: '1:518969593507:android:5a918725d084dc0bb7b916',
    messagingSenderId: '518969593507',
    projectId: 'bema-8f7d2',
    storageBucket: 'bema-8f7d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3gX3aYpisq3rDm700mjJOKOFrLY-NDF4',
    appId: '1:518969593507:ios:6c0317eaddfb655fb7b916',
    messagingSenderId: '518969593507',
    projectId: 'bema-8f7d2',
    storageBucket: 'bema-8f7d2.appspot.com',
    iosBundleId: 'com.example.bemaApplication',
  );
}
